name: pinkPower
description: A new Flutter project.


publish_to: 'none'


version: 1.0.2

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.5
  http: ^0.13.6
  fluttertoast: ^8.2.1
  google_maps_flutter: ^2.2.3
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  google_fonts: ^3.0.1
  image_picker: ^0.8.6
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  sms_otp_auto_verify: ^2.1.0
  shared_preferences: ^2.1.0
  flutter_phone_direct_caller: ^2.1.1
  url_launcher: ^6.1.9
  background_sms: ^0.0.4
  permission_handler: ^10.2.0
  flutter_tawk: ^0.1.0
  intl_phone_field:




dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/
     - assets/images/
     - assets/images/hospital.png
     - assets/images/ladies.png
     - assets/images/police.png
     - assets/images/hospital.png
